events {}

http{

	server {
		listen 443 ssl;
		server_name localhost;
		ssl_certificate ssl/inception.crt;
		ssl_certificate_key ssl/inception.key;
		ssl_protocols TLSv1.3;
		location / {
			return 200 "hello from 2cal\n";
		}
	}
}
