events {}

http{

	server {
		listen 443 ssl;
		server_name localhost;
		ssl_certificate /etc/cert.crt;
		ssl_certificate_key /etc/cert.key;
		ssl_protocols TLSv1.3;
		location / {
			return 200 "hello from 2cali\n";
		}
	}
}